CARS = {
    "BMW": ["X5", "X6", "X7", "5 Series", "M2", "M3", "M4", "M5", "M6", "M8", "i8"],
    "Toyota": ["Camry", "Land Cruiser", "RAV4", "Corolla", "Highlander", "Mark II", "Wish", "Harrier", "Alphard", "Corona", "Chaser", "Celica", "Sequoia", "Aristo", "MR2"],
    "Mercedes": ["E-Class", "S-Class", "GLE", "C-Class", "GLS", "Maybach S-Класс", "AMG GT", "CLS", "GLA", "CLS AMG", "GLA AMG", "SLR McLaren", "CLK"],
    "Audi": ["A6", "Q7", "A4", "A5", "A8", "RS 7", "RS 5"],
    "Lexus": ["RX", "LX", "ES", "NX", "IS", "GX", "LS", "GS", "UX", "LFA"],
    "Nissan": ["X-Trail", "Skyline", "Skyline R32", "Skyline R33", "Skyline R34", "GT-R", "Rogue", "Silvia", "180SX"],
    "Kia": ["K5", "K7", "K8", "K9", "Sportage", "Sorento", "RIO", "Sportage", "Sorento", "Optima", "Carnival", "Morning"],
    "Hyundai": ["Sonata", "Tucson", "Santa Fe", "Elantra", "Solaris", "Santa Fe", "Grandeur", "Kona", "Tiburon"],
    "Mazda": ["CX-5", "CX-9", "Mazda 6", "MX-5", "RX-7", "RX-8", "Atenza"],
    "Subaru": ["Forester", "Outback", "Impreza", "Impreza WRX", "Impreza WRX STI", "Legacy", "Crosstrek"],
    "Ford": ["Focus", "Explorer", "Mustang"],
    "Dodge": ["Charger", "Challenger", "Durango"],
    "Mitsubishi": ["Lancer", "Outlander", "Lancer Evolution", "Eclipse"],
    "Porsche": ["Cayenne", "Macan", "Panamera", "911", "Taycan", "Cayman", "911 GT3", "Boxster", "Carrera GT"],
    "Chevrolet": ["Tahoe", "Lacetti", "Spark", "Camaro", "Malibu", "Corvette", "Nexia", "Onix", "Impala", "Matiz"],
    "Honda": ["Civic", "Accord", "CR-V", "Stream", "Fit", "HR-V", "Stepwgn", "Odyssey", "Torneo", "Integra"],
    "Volkswagen": ["Passat", "Golf", "Jetta", "Lamando", "ID.5", "ID.7", "Touareg"],
    "Haval": ["Jolion", "F7", "F7x", "M6", "H7", "H8", "H9", "H6L", "Xiaolong"]
}